package utils

import (
	"log"
	"os"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
    // NOTE: This 'pb' package would be generated by the protoc compiler
	// for the shared gRPC service definition.
	// pb "github.com/MediBridge/go-api/pb" 
)

// The Go API will communicate with the AI Service using gRPC[cite: 107].
// Define a variable for the gRPC connection object.
var AIClientConn *grpc.ClientConn

// InitGRPCClient establishes the connection to the Python AI Microservice.
func InitGRPCClient() {
    // In a Docker/Docker Compose environment, we reference the service by its name.
    // The Python AI service is named 'ai-service' in the docker-compose.yml. [cite: 1]
	aiServiceHost := os.Getenv("AI_SERVICE_HOST") 
	if aiServiceHost == "" {
		aiServiceHost = "ai-service:50051" // Default address for the Docker service
	}

	// Set up connection to the gRPC server (Python AI Service)
	conn, err := grpc.Dial(
		aiServiceHost, 
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(), // Wait until the connection is established
	)
	if err != nil {
		log.Fatalf("did not connect to AI service: %v", err)
	}
    
	AIClientConn = conn
    log.Println("Successfully connected to AI Service via gRPC at:", aiServiceHost)
}

// CloseGRPCClient closes the connection when the Go API shuts down.
func CloseGRPCClient() {
	if AIClientConn != nil {
		if err := AIClientConn.Close(); err != nil {
			log.Printf("Error closing gRPC connection: %v", err)
		}
	}
}

// --- Placeholder gRPC Call Functions ---

// TriggerTranslationAndAudio (Called from Clinic App flow [cite: 124])
func TriggerTranslationAndAudio(prescriptionData models.Prescription) error {
    // In a real implementation:
    // 1. Create a gRPC client stub using AIClientConn.
    // 2. Call the remote procedure, sending prescriptionData.
    // 3. The Python service returns the TranslatedText and AudioFileURL. [cite: 125]
	log.Println("gRPC: Triggering translation and audio generation for Prescription ID:", prescriptionData.ID)
	// Example of a mock delay to simulate AI processing time
	time.Sleep(100 * time.Millisecond) 
	
	// TODO: Integrate actual gRPC client call here (e.g., pb.NewAIServiceClient)

	return nil
}

// TriggerReportProcessing (Called from Scanning Center App flow [cite: 90, 130])
func TriggerReportProcessing(reportID string, fileData []byte) error {
    // In a real implementation:
    // 1. Call the remote procedure, sending the report file data.
    // 2. The Python service performs Text Extraction and Simplification. [cite: 91, 131]
	log.Println("gRPC: Triggering report processing for Report ID:", reportID)
	// Example of a mock delay to simulate AI processing time
	time.Sleep(500 * time.Millisecond) 
	
	// TODO: Integrate actual gRPC client call here

	return nil
}

// QueryChatbot (Called from Patient App flow [cite: 65, 66])
func QueryChatbot(query string, patientID string) (string, error) {
    // In a real implementation:
    // 1. Call the remote procedure, sending the user query.
    // 2. The Python service processes the query and returns a conversational response. [cite: 66]
	log.Println("gRPC: Querying chatbot with:", query)
    
    // Mock response
	return "Hello! I am the MediBridge AI Chatbot. I can answer basic health queries and guide you through the app.", nil
}